# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7fbd67f379ef427300c82c2f7cede3efd725ee2a8c3eb644d981ebbb6e0823ead737ede3220e04c772b76a879a006b410b0ff04feb48141e0b98c06daf15aa2

test:
  secret_key_base: a6de0f0a95abfbe5b25f33a383bdfb7c092aeab4b86b4f3e6b5d6c6c2c821afddb0676e3a3e19af837b24c330b2e0e3190fee6c13902ba60d7efe2334ced03bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
